draft ASN APIs and ipinfo.io integration

diff --git a/Scripts/TestAll b/Scripts/TestAll
--- a/Scripts/TestAll
+++ b/Scripts/TestAll
@@ -1,4 +1,21 @@
 #!/bin/bash
 set -e
+
+# If JSON files are not present, download them from ipinfo.io
+for file in asn country ; do
+    if [ ! -f $file.json ]; then
+        if [ -z "$IPINFO_TOKEN" ]; then
+            echo "error: IPINFO_TOKEN is not set"
+            exit 1
+        fi
+
+        # Must follow redirects to get the actual file
+        curl -L https://ipinfo.io/data/free/$file.json.gz?token=$IPINFO_TOKEN -o $file.json.gz
+        gzip -d $file.json.gz
+    else
+        echo "Using existing $file.json"
+    fi
+done
+
 swift --version
 swift test -c release
